name: neural_inventory
channels:
  - apple
  - conda-forge
  - defaults
dependencies:
  - python=3.10.4
  - pip
  - numpy=1.22.4
  - pandas=1.4.3
  - matplotlib=3.5.1
  - scipy=1.7.3
  - scikit-learn=1.1.3
  - seaborn=0.11.2
  - statsmodels=0.13.2
  - jupyter
  - ipykernel
  - ipywidgets
  - tqdm
  - pyyaml
  - cloudpickle
  - gymnasium
  - mpmath
  - sympy
  - numexpr
  - setuptools
  - pip:
    - torch
    - torchvision
    - import-ipynb==0.1.4
    - nbconvert
    - nbimporter==0.3.4
