seeds:
  underage_cost: 28
  holding_cost: 73
  mean: 33
  coef_of_var: 92
  lead_time: 41
  demand: 57
  initial_inventory: 4839

test_seeds:
  # Seeds for test set
  underage_cost: 28
  holding_cost: 73
  mean: 33
  coef_of_var: 92
  lead_time: 41
  demand: 65
  initial_inventory: 4839

sample_data_params:
  split_by_period: false

problem_params:
  n_stores: 5 # Tested values: 3, 5, 10, 20, 30, 50
  n_warehouses: 1
  n_extra_echelons: 0
  lost_demand: true
  maximize_profit: false

params_by_dataset:
  train:
    n_samples: 8192 # Tested values: 16, 256, 8192 for vanilla and symmetry-aware (for sym-aware, additionally 2, 4, 8)
    batch_size: 1024
    periods: 50
    ignore_periods: 30
  dev:
    n_samples: 4096
    batch_size: 1024
    periods: 50
    ignore_periods: 30
  test:
    n_samples: 4096
    batch_size: 1024
    periods: 500
    ignore_periods: 300

observation_params:
  include_warehouse_inventory: true
  include_static_features:
    holding_costs: true
    underage_costs: true
    lead_times: true
    mean: true
    std: true
  demand:
    past_periods: 0
    period_shift: 0
  include_past_observations:
    arrivals: 0
    orders: 0
  include_days_to_christmas: false

store_params:
  demand:
    sample_across_stores: true
    mean_range:
      - 2.5
      - 7.5
    coef_of_var_range:
      - 0.25
      - 0.5
    distribution: normal
    correlation: 0.5
    clip: true
    decimals: 3
  lead_time:
    sample_across_stores: true
    vary_across_samples: false
    expand: false
    range:
      - 2
      - 4
      # Recall that upper range is excluded from the possible values
  holding_cost:
    sample_across_stores: true
    vary_across_samples: false
    expand: false
    range:
      - 0.7
      - 1.3
  underage_cost:
    sample_across_stores: true
    vary_across_samples: false
    expand: false
    range:
      - 6.3
      - 11.7
  initial_inventory:
    sample: true
    range_mult:
      - 0
      - 1
    inventory_periods: 3

warehouse_params:
  holding_cost: 0.3
  lead_time: 6

echelon_params: null